allow-branch = ["master", "window"]
sign-commit = true
sign-tag = true
target = "x86_64-unknown-linux-gnu"

pre-release-replacements = [
  {file="README.md", search='sabry = \{\s?version = "[0-9a-z\-\.]*"', replace='sabry = {version = "{{version}}"'},
]
