[package]
name = "sabry_build"
description = "Sabry build magic as a separate crate"
version.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sabry_intrnl.workspace = true
sabry_intrnl.features = ["compile", "scope"]
sabry_procmacro_impl.workspace = true
sabry_procmacro_impl.features = ["const-compile"]

syn.workspace = true
syn.features = ["visit", "derive", "parsing", "full"]
proc-macro2.workspace = true
proc-macro2.features = ["span-locations"]
thiserror.workspace = true
walkdir.workspace = true

[features]
net-files = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
