[package]
name = "sabry_intrnl"
description = "Sabry internal, yet still public library"
version.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
syn.workspace = true
raffia.workspace = true
regex.workspace = true
regex.optional = true
grass.workspace = true
grass.optional = true
lightningcss.workspace = true
lightningcss.optional = true
blake3.workspace = true
blake3.optional = true
base64.workspace = true
base64.optional = true

thiserror.workspace = true
serde.workspace = true
serde.features = ["derive"]
toml.workspace = true
cfg-if.workspace = true

[features]
scope = ["dep:blake3", "dep:base64", "dep:regex"]
compile = ["dep:lightningcss", "dep:grass"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
