[package]
name = "sabry_intrnl"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Sabry internal, yet still public library"
repository.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
base64.workspace = true
base64.optional = true
grass.workspace = true
grass.optional = true
lightningcss.workspace = true
lightningcss.optional = true
raffia.workspace = true
syn.workspace = true

cfg-if.workspace = true
serde.workspace = true
serde.features = ["derive"]
thiserror.workspace = true
toml.workspace = true

[features]
compile = ["dep:grass", "dep:lightningcss"]
scope = ["dep:base64"]
