[package]
name = "sabry_procmacro"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Sabry proc-macro declarations"
repository.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
proc-macro = true

[dependencies]
sabry_procmacro_impl.workspace = true

[features]
const-compile = ["sabry_procmacro_impl/const-compile"]
nightly = ["sabry_procmacro_impl/nightly"]
