[package]
name = "leptos-components"
version = "0.0.0"
rust-version = "1.88"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos.version = "^0.8"
leptos_meta.version = "^0.8"
leptos_router.version = "^0.8"
sabry.path = "../../"
sabry.features = ["const-scoping"]

[build-dependencies]
sabry.path = "../../"
sabry.features = ["build", "const-scoping"]
define-styles.version = "0.0.0"
define-styles.path = "../define-styles"

[features]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr"]

[package.metadata.sabry]
css.minify = true
# No need for bundle
# css.bundle = "target/.sabry/target/bundle.css"
